package:
  name: java-jdk
  version: 7.0.95

build:
  number: 1

source:
  fn: zulu7.13.0.1-jdk7.0.95-linux_x64.tar.gz
  md5: 00ed5a0c647ddf7ecd3f823cad23a3a8
  url: http://cdn.azul.com/zulu/bin/zulu7.13.0.1-jdk7.0.95-linux_x64.tar.gz

test:
  commands:
    - java -version

about:
  home: http://www.azulsystems.com/products/zulu
  summary: OpenJDK
  license: GPL
