package:
    name: knit
    version: 0.0.1

source:
    path: ../

requirements:
    build:
        - python
        - apache-maven
        - java-jdk [linux]
    run:
        - python

about:
  home: https://github.com/blaze/knit
  license: BSD
  summary: Python interface to Scala for interacting with YARN
